# Generated by Django 4.2.20 on 2025-03-21 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "file",
                    models.FileField(upload_to="csv_files/", verbose_name="CSV文件"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV文件",
                "verbose_name_plural": "CSV文件",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="字段1"
                    ),
                ),
                (
                    "field2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="字段2"
                    ),
                ),
                (
                    "field3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="字段3"
                    ),
                ),
                (
                    "field4",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="字段4"
                    ),
                ),
                (
                    "field5",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="字段5"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "csv_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="csv_upload.csvfile",
                        verbose_name="关联CSV文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据记录",
                "verbose_name_plural": "数据记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
