# Generated by Django 4.2.20 on 2025-04-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="專案名稱")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "專案",
                "verbose_name_plural": "專案",
                "db_table": "trees_project",
            },
        ),
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "_id",
                    models.AutoField(
                        db_column="_id", primary_key=True, serialize=False
                    ),
                ),
                ("species", models.TextField(verbose_name="樹種")),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="胸徑(cm)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="樹高(m)",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "record_date",
                    models.DateField(blank=True, null=True, verbose_name="記錄日期"),
                ),
                (
                    "project_id",
                    models.IntegerField(blank=True, null=True, verbose_name="專案ID"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "樹木",
                "verbose_name_plural": "樹木",
                "db_table": "trees",
            },
        ),
        migrations.CreateModel(
            name="TreeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="tree_images/", verbose_name="圖片"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="說明"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上傳時間"),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="trees.tree",
                        verbose_name="樹木",
                    ),
                ),
            ],
            options={
                "verbose_name": "樹木圖片",
                "verbose_name_plural": "樹木圖片",
                "db_table": "trees_treeimage",
            },
        ),
    ]
