# Generated by Django 4.2.20 on 2025-04-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tree_id", models.IntegerField()),
                ("action", models.CharField(max_length=20)),
                ("species", models.CharField(max_length=100)),
                (
                    "diameter",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("record_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trees.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
