# Generated by Django 4.2.20 on 2025-04-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_treehistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="treehistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "樹木歷史記錄",
                "verbose_name_plural": "樹木歷史記錄",
            },
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="action",
            field=models.CharField(max_length=20, verbose_name="操作類型"),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="diameter",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="胸徑(cm)"
            ),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="height",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="樹高(m)"
            ),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="備註"),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trees.project",
                verbose_name="專案",
            ),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="record_date",
            field=models.DateField(verbose_name="記錄日期"),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="species",
            field=models.CharField(max_length=100, verbose_name="樹種"),
        ),
        migrations.AlterField(
            model_name="treehistory",
            name="tree_id",
            field=models.IntegerField(verbose_name="樹木ID"),
        ),
    ]
