# Generated by Django 4.2.20 on 2025-04-17 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trees", "0003_alter_treehistory_options_alter_treehistory_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="創建者",
            ),
        ),
    ]
